# Generated by Django 2.2.1 on 2019-10-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_email', models.CharField(max_length=300)),
                ('event_name', models.CharField(max_length=100)),
                ('fback', models.CharField(max_length=600)),
            ],
        ),
    ]
