# Generated by Django 2.2.1 on 2019-10-09 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cseaweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='c_email',
            new_name='cemail',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='event_name',
            new_name='eventname',
        ),
    ]
